"""added fields to users. Many-to-many relaiton users

Revision ID: 0f56822e53ba
Revises: ef25615bcbbd
Create Date: 2022-08-08 23:04:41.662985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f56822e53ba'
down_revision = 'ef25615bcbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_mechanic',
    sa.Column('vehicle_owner_id', sa.Integer(), nullable=True),
    sa.Column('mechanic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mechanic'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['vehicle_owner_id'], ['vehicle_owner.id'], )
    )
    op.add_column('mechanic', sa.Column('company_name', sa.String(length=60), nullable=False))
    op.add_column('vehicle_owner', sa.Column('first_name', sa.String(length=20), nullable=False))
    op.add_column('vehicle_owner', sa.Column('last_name', sa.String(length=20), nullable=False))
    op.drop_constraint('vehicle_owner_mechanics_fkey', 'vehicle_owner', type_='foreignkey')
    op.drop_column('vehicle_owner', 'mechanics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_owner', sa.Column('mechanics', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vehicle_owner_mechanics_fkey', 'vehicle_owner', 'mechanic', ['mechanics'], ['id'])
    op.drop_column('vehicle_owner', 'last_name')
    op.drop_column('vehicle_owner', 'first_name')
    op.drop_column('mechanic', 'company_name')
    op.drop_table('owner_mechanic')
    # ### end Alembic commands ###
