"""vehicles mechanic many to many fix

Revision ID: 534e1ba2a3f4
Revises: f62192d47b40
Create Date: 2022-08-17 21:15:20.855627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534e1ba2a3f4'
down_revision = 'f62192d47b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner_mechanic', sa.Column('mechanic_id', sa.Integer(), nullable=True))
    op.drop_constraint('owner_mechanic_mechanic_fkey', 'owner_mechanic', type_='foreignkey')
    op.create_foreign_key(None, 'owner_mechanic', 'mechanic', ['mechanic_id'], ['id'])
    op.drop_column('owner_mechanic', 'mechanic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner_mechanic', sa.Column('mechanic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'owner_mechanic', type_='foreignkey')
    op.create_foreign_key('owner_mechanic_mechanic_fkey', 'owner_mechanic', 'mechanic', ['mechanic'], ['id'])
    op.drop_column('owner_mechanic', 'mechanic_id')
    # ### end Alembic commands ###
