"""added phone number to user base

Revision ID: d66d81ae6672
Revises: c72ac94c1104
Create Date: 2022-08-22 20:48:58.140622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66d81ae6672'
down_revision = 'c72ac94c1104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('phone_number', sa.String(length=14), nullable=False))
    op.add_column('mechanic', sa.Column('phone_number', sa.String(length=14), nullable=False))
    op.add_column('vehicle_owner', sa.Column('phone_number', sa.String(length=14), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_owner', 'phone_number')
    op.drop_column('mechanic', 'phone_number')
    op.drop_column('admin', 'phone_number')
    # ### end Alembic commands ###
