"""fixing foreign key

Revision ID: e6277659a3c1
Revises: 534e1ba2a3f4
Create Date: 2022-08-18 01:01:28.555602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6277659a3c1'
down_revision = '534e1ba2a3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_vehicle_owner_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'vehicle_owner', ['vehicle_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_vehicle_owner_id_fkey', 'offer', 'vehicle', ['vehicle_owner_id'], ['id'])
    # ### end Alembic commands ###
