"""owner id added to offer model

Revision ID: f62192d47b40
Revises: bdcbc9878d0a
Create Date: 2022-08-16 20:35:44.159834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62192d47b40'
down_revision = 'bdcbc9878d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('vehicle_owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'offer', 'vehicle', ['vehicle_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'vehicle_owner_id')
    # ### end Alembic commands ###
